export const SKILLS = [
  { name: 'React + Vite', level: 95, icon: '⚛️', color: 'rgba(167,139,250,0.12)', desc: 'Ultra-fast SPA development with modern tooling' },
  { name: 'Three.js / R3F', level: 80, icon: '🌌', color: 'rgba(96,165,250,0.12)', desc: 'Immersive 3D experiences and GPU-accelerated effects' },
  { name: 'Framer Motion', level: 90, icon: '🎬', color: 'rgba(52,211,153,0.12)', desc: 'Physics-based animations and gesture-driven interactions' },
  { name: 'Zustand + RQ', level: 88, icon: '🧠', color: 'rgba(251,191,36,0.12)', desc: 'Minimal, scalable state and server-state management' },
  { name: 'TailwindCSS', level: 97, icon: '🎨', color: 'rgba(239,68,68,0.12)', desc: 'Utility-first styling with custom design tokens' },
  { name: 'Node.js + APIs', level: 75, icon: '🔗', color: 'rgba(99,102,241,0.12)', desc: 'RESTful and GraphQL API design with integrations' },
  { name: 'Python', level: 85, icon: '🐍', color: 'rgba(52,211,153,0.1)', desc: 'Data processing, automation, backend scripting and AI integrations' },
  { name: 'C++', level: 70, icon: '⚙️', color: 'rgba(251,191,36,0.1)', desc: 'System-level programming, algorithms and high-performance computing' },
]

export const STATS = [
  { label: 'Projects Built', target: 24, suffix: '+' },
  { label: 'GitHub Stars', target: 180, suffix: '+' },
  { label: 'Technologies', target: 15, suffix: '+' },
]

export const NAV_LINKS = [
  { label: 'Home', id: 'home' },
  { label: 'Skills', id: 'skills' },
  { label: 'Projects', id: 'projects' },
  { label: 'Contact', id: 'contact' },
]

export const LANG = {
  uz: {
    available: 'Ish uchun ochiq',
    title1: 'MurodovShohruh',
    title2: 'ASC',
    tagline: "Keng miqyosli kod me'mori — elegantli, tez va kelajakbop raqamli tajribalar yaratuvchi.",
    viewProjects: "Proyektlarni ko'rish",
    getInTouch: "Bog'lanish →",
    scroll: "Scroll",
    skills: 'Mahorat',
    techStack: 'Tech Stack',
    portfolio: 'Portfolio',
    featured: 'Tanlangan Proyektlar',
    letsConnect: "Bog'lanaylik",
    readyToBuild: 'Birgalikda <gradient>ajoyib</gradient> narsa yasaymizmi?',
    contactDesc: "Freelance, hamkorlik va qiziqarli imkoniyatlar uchun ochiqman. Keling, unutilmas narsa yarataylik.",
    sendMsg: "Xabar yuborish →",
    footerBuilt: 'React + Three.js bilan qurilgan',
  },
  en: {
    available: 'Available for hire',
    title1: 'MurodovShohruh',
    title2: 'ASC',
    tagline: 'Architect of Scalable Code — building elegant, performant, and future-proof digital experiences.',
    viewProjects: 'View Projects',
    getInTouch: 'Get in touch →',
    scroll: 'Scroll',
    skills: 'Expertise',
    techStack: 'Tech Stack',
    portfolio: 'Portfolio',
    featured: 'Featured Projects',
    letsConnect: "Let's Connect",
    readyToBuild: 'Ready to build something <gradient>extraordinary?</gradient>',
    contactDesc: 'Open to freelance projects, collaborations, and exciting opportunities. Let\'s create something unforgettable together.',
    sendMsg: 'Send a message →',
    footerBuilt: 'Built with React + Three.js',
  },
  ru: {
    available: 'Открыт для работы',
    title1: 'MurodovShohruh',
    title2: 'ASC',
    tagline: 'Архитектор масштабируемого кода — создаю элегантные, быстрые и перспективные цифровые решения.',
    viewProjects: 'Смотреть проекты',
    getInTouch: 'Связаться →',
    scroll: 'Scroll',
    skills: 'Навыки',
    techStack: 'Стек технологий',
    portfolio: 'Портфолио',
    featured: 'Избранные проекты',
    letsConnect: 'Давайте свяжемся',
    readyToBuild: 'Готовы создать что-то <gradient>грандиозное?</gradient>',
    contactDesc: 'Открыт для фриланса, коллабораций и интересных возможностей. Давайте создадим что-то незабываемое.',
    sendMsg: 'Написать →',
    footerBuilt: 'Создано на React + Three.js',
  },
}
